dist: trusty
sudo: required
matrix:
  include:
    - language: python
      python:
        - "3.6"
      cache:
        directories:
          - $HOME/.cache/pip
      services: 
        - postgresql
        - redis-server
      env:
        global:
        - DJANGO_SETTINGS_MODULE=photomy.settings.travis
        - PYTHONPATH="/home/travis/build/meemaw/photomy"
        - PIP_USE_MIRRORS=true
      install:
        - pip install -U pip wheel
        - pip install -r config/requirements.txt
      before_script:
        - psql -c "CREATE DATABASE travisci;" -U postgres
        - cd src
        - python manage.py migrate --noinput --settings=photomy.settings.travis
      script:
        - coverage run manage.py test --settings=photomy.settings.travis --noinput --keepdb --parallel
      after_success:
        - bash <(curl -s https://codecov.io/bash) -F python -t $CODECOV_UPLOAD_TOKEN
    - language: node_js
      node_js:
        - "node"
      before_script:
        - cd frontend
        - yarn install
      cache:
        yarn: true
        directories:
          - $HOME/.npm
      script:
        - yarn test-coverage
      after_success:
        - codecov -F javascript -t $CODECOV_UPLOAD_TOKEN
        


