language: python
cache: pip

python:
  - "3.6"

services: postgresql

env:
  global:
  - DJANGO_SETTINGS_MODULE=photomy.settings.travis
  - PYTHONPATH="/home/travis/build/meemaw/photomy"
  - PIP_USE_MIRRORS=true

install:
  - pip install -r config/requirements.txt

before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres
  - cd src
  - python manage.py migrate --noinput --settings=photomy.settings.travis

script:
  - python manage.py test --settings=photomy.settings.travis --noinput --keepdb