dist: trusty
sudo: required
matrix:
  include:
    - stage: test
      language: python
      python:
        - "3.6"
      node_js:
        - "node"
      services: 
        - redis-server
        - postgresql
      cache:
        yarn: true
        directories:
          - $HOME/e2etests/.npm
          - $HOME/.cache/pip  
      env:
        global:
        - DJANGO_SETTINGS_MODULE=photomy.settings.travis
        - PYTHONPATH="/home/travis/build/meemaw/photomy"
        - PIP_USE_MIRRORS=true
      before_install:
        - export CHROME_BIN=/usr/bin/google-chrome
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - sudo apt-get update
        - sudo apt-get install -y libappindicator1 fonts-liberation
        - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        - sudo dpkg -i google-chrome*.deb
      install:
        - pip install -U pip wheel
        - pip install -r config/requirements.txt
        - psql -c "CREATE DATABASE travisci;" -U postgres
        - cd src
        - python manage.py migrate --noinput --settings=photomy.settings.travis
        - python manage.py populate_test_users --settings=photomy.settings.travis
        - python manage.py runserver 0.0.0.0:8000 --settings=photomy.settings.travis 2>&1 > /dev/null &
        - cd ../frontend
        - yarn install
        - export CONTAINNER_ADDRESS=$(/sbin/ip -o -4 addr list eth0 | awk '{print $4}' | cut -d/ -f1)
        - node_modules/gulp/bin/gulp.js --gulpfile ./gulpfile.js setTravis
        - sed -i "s/localhost/$CONTAINNER_ADDRESS/g" ./src/environments/travis.json
        - BROWSER=none yarn start  2>&1 > /dev/null &
        - cd e2etests
        - yarn install
      script:
        - curl http://localhost:8000/rest-auth/login/
        - curl http://127.0.0.1:8000/rest-auth/login/
        - curl http://0.0.0.0:8000/rest-auth/login/
        - export PHOTOMY_URL="http://$CONTAINNER_ADDRESS:3000/"
        - yarn test

  

stages:
  - test
  - build
  - deploy
