dist: trusty
sudo: required
matrix:
  include:
    - stage: test
      language: python
      python:
        - "3.6"
      cache:
        directories:
          - $HOME/.cache/pip
      services:
        - postgresql
        - redis-server
        - docker
      env:
        global:
          - DJANGO_SETTINGS_MODULE=photomy.settings.test.travis
          - PYTHONPATH="/home/travis/build/meemaw/photomy"
          - PIP_USE_MIRRORS=true
      install:
        - pip install -U pip wheel
        - pip install -r config/requirements.txt
      before_script:
        - psql -c "CREATE DATABASE travisci;" -U postgres
        - cd src
        - python manage.py migrate --noinput --settings=photomy.settings.test.travis
      script:
        - pytest --cov --ds=photomy.settings.test.travis
      after_success:
        - bash <(curl -s https://codecov.io/bash) -F python -t $CODECOV_UPLOAD_TOKEN

    - stage: test
      language: node_js
      node_js:
        - "node"
      before_script:
        - cd frontend
        - yarn install
      cache:
        yarn: true
        directories:
          - $HOME/.npm
      script:
        - yarn lint
        - yarn test-coverage
      after_success:
        - codecov -F javascript -t $CODECOV_UPLOAD_TOKEN

    - stage: test
      language: python
      python:
        - "3.6"
      node_js:
        - "9.8"
      services:
        - redis-server
        - postgresql
      cache:
        yarn: true
        directories:
          - $HOME/e2etests/.npm
          - $HOME/.cache/pip
      env:
        global:
          - DJANGO_SETTINGS_MODULE=photomy.settings.test.travise2e
          - PYTHONPATH="/home/travis/build/meemaw/photomy"
          - PIP_USE_MIRRORS=true
      before_install:
        - export CHROME_BIN=/usr/bin/google-chrome
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - sudo apt-get update
        - sudo apt-get install -y libappindicator1 fonts-liberation
        - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        - sudo dpkg -i google-chrome*.deb
      install:
        - pip install -U pip wheel
        - pip install -r config/requirements.txt
        - psql -c "CREATE DATABASE travisci;" -U postgres
        - cd src
        - export CONTAINNER_ADDRESS=$(/sbin/ip -o -4 addr list eth0 | awk '{print $4}' | cut -d/ -f1)
        - python manage.py migrate --noinput --settings=photomy.settings.test.travise2e
        - python manage.py populate_test_users --settings=photomy.settings.test.travise2e
        - python manage.py populate_test_images --settings=photomy.settings.test.travise2e
        - python manage.py runserver --settings=photomy.settings.test.travise2e 2>&1 > /dev/null &
        - cd ../frontend
        - yarn install
        - node_modules/gulp/bin/gulp.js --gulpfile ./gulpfile.js setTravis
        - BROWSER=none yarn start  2>&1 > /dev/null &
        - cd e2etests
        - yarn install
      script:
        - export PHOTOMY_URL="http://localhost:3000"
        - yarn test
        - cd ../../src
        - python manage.py clean_images --settings=photomy.settings.test.travise2e ## To delete images from s3

    - stage: build
      if: branch = master
      language: bash
      script:
        - echo -e "AWS_ACCESS_KEY_ID=\"$AWS_ACCESS_KEY_ID\"
          AWS_SECRET_ACCESS_KEY=\"$AWS_SECRET_ACCESS_KEY\"
          DJANGO_SECRET_KEY=\"$DJANGO_SECRET_KEY\"
          AWS_CLOUDFRONT_DOMAIN=\"$AWS_CLOUDFRONT_DOMAIN\"
          TEST_AWS_CLOUDFRONT_DOMAIN=\"$TEST_AWS_CLOUDFRONT_DOMAIN\"
          AWS_LAMBDA_SECRET_APP_KEY=\"$AWS_LAMBDA_SECRET_APP_KEY\"
          AWS_LAMBDA_SECRET_APP_VALUE=\"$AWS_LAMBDA_SECRET_APP_VALUE\"
          EMAIL_HOST_PASSWORD=\"$EMAIL_HOST_PASSWORD\"
          EMAIL_HOST_USER=\"$EMAIL_HOST_USER\"
          AWS_STORAGE_BUCKET_NAME=\"$AWS_STORAGE_BUCKET_NAME\"
          TEST_AWS_STORAGE_BUCKET_NAME=\"$TEST_AWS_STORAGE_BUCKET_NAME\"
          POSTGRES_PASSWORD=\"$POSTGRES_PASSWORD\"
          " > src/.env
        - docker build . -t meemaw/photomy:latest
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push meemaw/photomy:latest

    - stage: build
      if: tag IS present AND tag =~ ^backend-v.*$
      language: bash
      script:
        - RELEASE_TAG=$(echo $TRAVIS_TAG | cut -d 'v' -f 2)
        - echo "Building docker image version:" $RELEASE_TAG
        - docker build . -t meemaw/photomy:$RELEASE_TAG
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - echo "Pushing docker image version:" $RELEASE_TAG
        - docker push meemaw/photomy:$RELEASE_TAG

    - stage: deploy
      if: tag IS present AND tag =~ ^frontend-v.*$
      language: node_js
      node_js:
        - "node"
      before_script:
        - RELEASE_TAG=$(echo $TRAVIS_TAG | cut -d 'v' -f 2)
        - echo "Deploying frontend version:" $RELEASE_TAG
        - cd frontend
        - 'echo "export const VERSION_INFO = { tag: ''$RELEASE_TAG'', branch: ''$TRAVIS_BRANCH'', commit: ''$TRAVIS_COMMIT'' }" > ./src/version.js'
        - yarn install
        - sudo pip install --upgrade pip
        - sudo pip install awscli
      cache:
        yarn: true
        directories:
          - $HOME/.npm
      script:
        - gulp setProd
        - yarn build
        - aws s3 sync build s3://photomy.si --delete
      after_success:
        - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"

stages:
  - test
  - build
  - deploy
