version: '3'

services:
  worker:
    image: meemaw/photomy:${VERSION}
    volumes:
      - /home/ubuntu/photomy/src/.env:/src/.env
  db:
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  web:
    image: meemaw/photomy:${VERSION}
    restart: always
    command: uwsgi --ini /etc/uwsgi/conf.d/uwsgi.ini
    expose:
      - "8000"
    volumes:
      - /home/ubuntu/photomy/config/uwsgi:/etc/uwsgi/conf.d
      - /home/ubuntu/photomy/src/.env:/src/.env
      - /tmp/uwsgi:/tmp/uwsgi
  nginx:
    restart: always
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ubuntu/photomy/config/nginx:/etc/nginx/conf.d
      - /home/ubuntu/photomy/config/uwsgi:/etc/uwsgi/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - web