version: '3'

services:
  db:
    ports:
      - "5432:5432"
  web:
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/src
    ports:
      - "8000:8000"
volumes:
  pgdata: