# Generated by Django 2.0.4 on 2018-06-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20180615_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
