# Generated by Django 2.0.4 on 2018-06-22 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20180616_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='rejected_identities',
        ),
    ]
