# Generated by Django 2.0.4 on 2018-06-23 06:42

from django.db import migrations, models
import gallery.constants


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_remove_image_rejected_identities'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='processing_status',
            field=models.CharField(choices=[(gallery.constants.ProcessingStatus('Initial'), 'Initial'), (gallery.constants.ProcessingStatus('In queue'), 'In queue'), (gallery.constants.ProcessingStatus('Processing'), 'Processing'), (gallery.constants.ProcessingStatus('Processed'), 'Processed'), (gallery.constants.ProcessingStatus('User disabled'), 'User disabled')], default=gallery.constants.ProcessingStatus('Initial'), max_length=30),
        ),
    ]
