# Generated by Django 2.0.4 on 2018-06-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_image_processing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='taken_on',
            field=models.DateTimeField(null=True),
        ),
    ]
