# Generated by Django 2.0.4 on 2018-06-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_image_taken_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
