// @flow

export const SET_GALLERY_TYPE = 'SET_GALLERY_TYPE';
export const SET_AUTH_USER = 'SET_AUTH_USER';
export const SET_AUTH_TOKEN_CHECKED = 'SET_AUTH_TOKEN_CHECKED';
export const LOGOUT = 'LOGOUT';
export const AUTHORIZE = 'AUTHORIZE';
export const SET_IDENTITY = 'SET_IDENTITY';
export const SET_MENU = 'SET_MENU';

export const FETCH_IMAGES = 'FETCH_IMAGES';
export const FETCHING_IMAGES = 'FETCHING_IMAGES';

export const UPLOAD_IMAGES = 'UPLOAD_IMAGES';
export const DELETE_IMAGE = 'DELETE_IMAGE';

export const FAVORITE_IMAGE = 'FAVORITE_IMAGE';

export const SET_ALBUM_NAME = 'SET_ALBUM_NAME';
export const SET_ALBUM_QUALITY = 'SET_ALBUM_QUALITY';
export const ADD_ACCEPTED_UPLOADS = 'ADD_ACCEPTED_UPLOADS';
export const RESET_UPLOADING_STATE = 'RESET_UPLOADING_STATE';

export const SET_IS_ALBUM = 'SET_IS_ALBUM';

export const SET_RECOGNIZE_PEOPLE = 'SET_RECOGNIZE_PEOPLE';

export const REMOVE_FILE = 'REMOVE_FILE_UPLOAD';
export const UPLOAD_FILES = 'UPLOAD_FILES';
export const SET_UPLOADING_IMAGES = 'SET_UPLOADING_IMAGES';
export const SET_IMAGE_UPLOADED = 'SET_IMAGE_UPLOADED';
export const SET_UPLOAD_WITH_LINK = 'SET_UPLOAD_WITH_LINK';

export const SET_ALBUM = 'SET_ALBUM';
export const SET_ALBUM_DELETING = 'SET_ALBUM_DELETING';
