// @flow

// Gallery
export const FETCH_IMAGES = 'FETCH_IMAGES';
export const SET_FETCHING_IMAGES = 'SET_FETCHING_IMAGES';
export const UPLOAD_IMAGES = 'UPLOAD_IMAGES';
export const UPDATE_IMAGE = 'UPDATE_IMAGE';
export const DELETE_IMAGE = 'DELETE_IMAGE';
export const FAVORITE_IMAGE = 'FAVORITE_IMAGE';

// Auth
export const SET_AUTH_USER = 'SET_AUTH_USER';
export const SET_AUTH_TOKEN_CHECKED = 'SET_AUTH_TOKEN_CHECKED';
export const LOGOUT = 'LOGOUT';
export const AUTHORIZE = 'AUTHORIZE';

// Identity
export const SET_IDENTITY = 'SET_IDENTITY';

// Ui
export const SET_GALLERY_TYPE = 'SET_GALLERY_TYPE';
export const SET_APP_ERROR = 'SET_APP_ERROR';

// Album
export const SET_ALBUM = 'SET_ALBUM';
export const SET_ALBUM_DELETING = 'SET_ALBUM_DELETING';
export const DELETE_ALBUM_GALLERIES = 'DELETE_ALBUM_GALLERIES';
export const RENAME_ALBUM = 'RENAME_ALBUM';

// Albums
export const SET_ALBUMS_FETCHING = 'SET_ALBUMS_FETCHING';
export const SET_ALBUMS = 'SET_ALBUMS';
export const ADD_ALBUM = 'ADD_ALBUM';
export const ADD_ALBUM_TO_IMAGE = 'ADD_ALBUM_TO_IMAGE';
export const SET_ALBUM_COVER_IMAGE = 'SET_ALBUM_COVER_IMAGE';
export const REMOVE_IMAGE_FROM_ALBUM = 'REMOVE_IMAGE_FROM_ALBUM';
