# Generated by Django 2.0.4 on 2018-06-03 13:47

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('identity', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageIdentityMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_index', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed', models.BooleanField(default=True)),
                ('match_confidence', models.FloatField(default=1.0)),
                ('rejected_identities', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('identity_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_group', to='identifier.IdentityGroup')),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_matches', to='gallery.Image')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
